[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/admin/generator"
  to = "/admin/generator/"
  status = 301

[[redirects]]
  from = "/admin/ranking"
  to = "/admin/ranking/"
  status = 301

[[redirects]]
  from = "/admin/canon"
  to = "/admin/canon/"
  status = 301

[[redirects]]
  from = "/generator"
  to = "/admin/generator/"
  status = 301

[[redirects]]
  from = "/generator/*"
  to = "/admin/generator/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/canon"
  to = "/admin/canon/"
  status = 301

[[redirects]]
  from = "/canon/*"
  to = "/admin/canon/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/test"
  to = "/admin/generator/"
  status = 301
  force = true

[[redirects]]
  from = "/admin/test/*"
  to = "/admin/generator/"
  status = 301
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
