-- Tattoo Dice Admin Ranking storage
-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.

create table if not exists public.admin_rankings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  theme text not null check (theme in ('classic','fantasy')),
  dice_count smallint not null check (dice_count between 1 and 3),
  selected_main text not null default 'Random',
  words jsonb not null,
  combination_key text not null,
  rating text not null check (rating in ('up','down','open')),
  note text,
  user_agent text
);

create index if not exists admin_rankings_created_at_idx
  on public.admin_rankings (created_at desc);

create index if not exists admin_rankings_combination_key_idx
  on public.admin_rankings (combination_key);

create index if not exists admin_rankings_rating_idx
  on public.admin_rankings (rating);

alter table public.admin_rankings enable row level security;

drop policy if exists "Public admin ranking insert" on public.admin_rankings;
create policy "Public admin ranking insert"
on public.admin_rankings
for insert
to anon
with check (true);

drop policy if exists "Public admin ranking read" on public.admin_rankings;
create policy "Public admin ranking read"
on public.admin_rankings
for select
to anon
using (true);

-- Optional: the page does not update or delete records.
-- Keep update/delete unavailable for the public anon key.


drop policy if exists "Public admin ranking delete" on public.admin_rankings;
create policy "Public admin ranking delete"
on public.admin_rankings
for delete
to anon
using (true);
